spring.application.name=webhook-buffer-engine

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=3s
spring.rabbitmq.listener.simple.retry.max-attempts=3

rabbitmq.queue.name=webhookQueue
rabbitmq.exchange.name=webhookExchange
rabbitmq.routing.key=webhookRoutingKey